version: 0.2

phases:
  install:
    commands:
      - echo "[+] Scanning for security vulnerability within dependencies"
      # - pipenv check (if pipenv is installed and a Pipfile is in place)
      # - Alternatively: https://www.owasp.org/index.php/OWASP_Dependency_Check
  pre_build:
    commands:
      - pip install flask
      - echo "[+] Running tests..."
      # - python -m pytest tests/ -v
  build:
    commands:
      - echo "[+] Installing dependencies...."
      - mkdir dist
      - pip install -r requirements.txt -t dist/
      - cp *.py dist/
      - cp requirements.txt dist/
      - cp -R templates dist/
      - echo "Starting  packaging `date` in `pwd`"
      - zip -r dist.zip dist
  post_build:
    commands:
      - echo "Packaging completed on `date`"

artifacts:
  files:
    - dist/**/*
  discard-paths: yes

cache:
  paths:
    - '/root/.cache/pip'